-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employee
(
    id bigint NOT NULL DEFAULT nextval('employee_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    identification character varying(20) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employee_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.routeinfo
(
    id bigint NOT NULL DEFAULT nextval('routeinfo_id_seq'::regclass),
    sector character varying(20) COLLATE pg_catalog."default" NOT NULL,
    neighborhoods text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT routeinfo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scheduleinfo
(
    id bigint NOT NULL DEFAULT nextval('scheduleinfo_id_seq'::regclass),
    route_id smallint NOT NULL,
    truck_id smallint NOT NULL,
    hour_exit character varying COLLATE pg_catalog."default" NOT NULL,
    hour_arrival character varying COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT scheduleinfo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.truckinfo
(
    id bigint NOT NULL DEFAULT nextval('truckinfo_id_seq'::regclass),
    number_registratior character varying(10) COLLATE pg_catalog."default" NOT NULL,
    capacity bigint NOT NULL,
    CONSTRAINT truckinfo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL,
    username character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.scheduleinfo
    ADD CONSTRAINT scheduleinfo_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.scheduleinfo
    ADD CONSTRAINT scheduleinfo_route_id_fkey FOREIGN KEY (route_id)
    REFERENCES public.routeinfo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.scheduleinfo
    ADD CONSTRAINT scheduleinfo_truck_id_fkey FOREIGN KEY (truck_id)
    REFERENCES public.truckinfo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;